production pathways:
  ADD:
    production volume:
      variable: Production|Baking|Bread|Activated Dough Development
    efficiency:
      variable: Efficiency|Baking|Bread|Activated Dough Development
    ecoinvent alias:
      exists in ecoinvent: False
      name: bread production, activated dough development
      reference product: bread
    except regions:
      - BRA
  SDM:
    production volume:
      variable: Production|Baking|Bread|Straight Dough Method
    efficiency:
      variable: Efficiency|Baking|Bread|Straight Dough Method
    ecoinvent alias:
      exists in ecoinvent: False
      name: bread production, straight dough method
      reference product: bread
    except regions:
      - USA

  DSM:
    production volume:
      variable: Production|Baking|Bread|Delayed Salt Method
    efficiency:
      variable: Efficiency|Baking|Bread|Delayed Salt Method
    ecoinvent alias:
      exists in ecoinvent: False
      name: bread production, delayed salt method
      reference product: bread
    except regions:
      - WEU
      - USA

markets:
  name: market for bread
  reference product: bread
  unit: kilogram
  includes:
    - bread production, activated dough development
    - bread production, straight dough method
    - bread production, delayed salt method
  replaces:
    name: market for carbon black
    reference product: carbon black
  except regions:
    - JAP



