{% set data = load_setup_py_data() %}

package:
  name: premise
  version: {{ data['version'] }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
  run:
    - brightway2
    - numpy
    - pandas
    - bw2io >=0.8
    - bw2data
    - wurst >=0.3
    - xarray <0.18
    - prettytable
    - carculator
    - carculator_truck
    - pycountry
    - cryptography

test:
  imports:
    - premise

about:
  home: https://github.com/romainsacchi/premise
  license: BSD License
  summary: 'Coupling Integrated Assessment Models and Life Cycle Assessment.'
license_family: BSD