package:
  name: premise
  version: {{ environ['VERSION'] }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  script_env:
    - VERSION
    - CONDA_BLD_PATH

requirements:
  build:
    - python
    - setuptools
  run:
    - brightway2
    - numpy
    - pandas
    - bw2io >=0.8
    - bw2calc>=1.8.1
    - bw2data
    - wurst ==0.3.0
    - xarray <0.18
    - prettytable
    - pycountry
    - cryptography
    - pyYaml
    - schema

test:
  imports:
    - premise

about:
  home: https://github.com/polca/premise
  license: BSD License
  summary: 'Coupling Integrated Assessment Models and Life Cycle Assessment.'
license_family: BSD