package:
  name: rmnd-lca
  version: {{ environ['VERSION'] }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: python pip install .
  script_env:
   - VERSION
   - CONDA_BLD_PATH

requirements:
  build:
    - python
    - setuptools
    - wurst
  run:
    - python

test:
  imports:
    - rmnd_lca

about:
  home: https://github.com/romainsacchi/rmnd-lca
  license: BSD License
  summary: 'Coupling REMIND output to ecoinvent LCA databases.'
license_family: BSD
