package:
  name: premise
  version: {{ environ['VERSION'] }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  script_env:
   - VERSION
   - CONDA_BLD_PATH

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - wurst
    - numpy
    - pandas
    - bw2io
    - bw2data
    - xarray
    - prettytable
    - carculator
    - carculator_truck
    - pycountry
    - cryptography
    - premise_gwp

test:
  imports:
    - premise

about:
  home: https://github.com/romainsacchi/premise
  license: BSD License
  summary: 'Coupling Integrated Assessment Model (IAM) scenarios output with ecoinvent inventory database.'
license_family: BSD
